### ISSUE TITLE
Question on training steps different from paper

### ISSUE THREAD

**Issue by e96031413** [dvirsamuel/DRAGON#1]
Hi, I found that the training steps you provided in README file seems to be different from your paper (Section D.) Am I misunderstanding your paper? Thanks

### Section D.:

First, we train each expert on the training data excluding the hold-out set. Second, we freeze the expert weights and train the fusion-module on all the training set. Finally, we re-train the experts on all the training data in order to use all data available.

### README:

First, train each expert without the hold-out set (partial training set)
Then, re-train each expert, with the hold-out set
Train the fusion-module on trained experts
Finally, evaluate the fusion-module with fully-trained experts

**Comment by dvirsamuel** [comment]
Hi,
The two are basically the same.
The fusion module is trained on all the data, with experts that were trained on the data excluding the held-out set (first step). 
In our implementation, it does not matter whether you re-train the experts after training the fusion module or before since it uses the experts from the first step.

I changed the readme to make it more clear. Thanks.
